import {
  Globe,
  LayoutTemplate,
  LogIn,
  ShoppingCart,
  Database,
  Bot,
} from "lucide-react";
import type { SolutionTypeCardItem } from "../../components/SolutionTypeCards";

export const types: SolutionTypeCardItem[] = [
  {
    id: "One-Page",
    icon: <Globe size="var(--size-22)" color="var(--color-surface)" />,
    accentColor: "var(--color-blue-600)",
    color: "linear-gradient(var(--value-135deg), var(--color-blue-600), var(--color-blue-700))",
    title: "Site de Uma Página (One Page)",
    sub: "Ideal para começar",
    desc: "Um único endereço na internet com tudo o que você faz: seus serviços, contato, redes sociais. Perfeito para quem quer aparecer no Google sem complicação.",
    checks: [
      "Aparece no Google (SEO)",
      "Sem banco de dados",
      "Funciona no celular e computador",
      "Formulário de contato simples",
    ],
    tag: { label: "Mais simples", variant: "green" as const },
  },
  {
    id: "Site",

    icon: <LayoutTemplate size="var(--size-22)" color="var(--color-surface)" />,
    accentColor: "var(--color-cyan-600)",
    color: "linear-gradient(var(--value-135deg), var(--color-cyan-600), var(--color-cyan-700))",
    title: "Site com Várias Páginas",
    sub: "Sobre nós, serviços, portfólio...",
    desc: "Quando você tem mais conteúdo para mostrar: um menu com páginas separadas para cada assunto — empresa, produtos, blog, contato.",
    checks: [
      "Páginas organizadas com menu",
      "Blog ou notícias (opcional)",
      "Galeria de fotos ou portfólio",
      "Otimizado para Google",
    ],
    tag: { label: "Popular", variant: "blue" as const },
  },
  {
    id: "Login",
    icon: <LogIn size="var(--size-22)" color="var(--color-surface)" />,
    accentColor: "var(--color-purple-600)",
    color: "linear-gradient(var(--value-135deg), var(--color-purple-600), var(--color-purple-700))",
    title: "Sistema com Login",
    sub: "Cada usuário vê o que é seu",
    desc: "Quando você precisa que clientes ou funcionários entrem com usuário e senha para acessar uma área privada com seus dados.",
    checks: [
      "Cadastro e login de usuários",
      "Área privada por perfil",
      "Banco de dados seguro",
      "Recuperação de senha",
    ],
    tag: { label: "Intermediário", variant: "purple" as const },
  },
  {
    id: "Loja",
    icon: <ShoppingCart size="var(--size-22)" color="var(--color-surface)" />,
    accentColor: "var(--color-amber-600)",
    color: "linear-gradient(var(--value-135deg), var(--color-amber-600), var(--color-amber-700))",
    title: "Loja Virtual",
    sub: "Venda pela internet",
    desc: "Uma loja online completa onde seus clientes podem navegar pelos produtos, colocar no carrinho e pagar — tudo pelo computador ou celular.",
    checks: [
      "Catálogo de produtos",
      "Carrinho e checkout",
      "Pagamento online (Pix, cartão)",
      "Painel de pedidos para você",
    ],
    tag: { label: "Intermediário", variant: "orange" as const },
  },
  {
    id: "Banco",
    icon: <Database size="var(--size-22)" color="var(--color-surface)" />,
    accentColor: "var(--color-green-500)",
    color: "linear-gradient(var(--value-135deg), var(--color-green-500), var(--color-green-700))",
    title: "Sistema Completo com Banco",
    sub: "Profissional e escalável",
    desc: "Para negócios que precisam de algo mais robusto: controle de clientes, pedidos, estoque, relatórios — tudo centralizado e acessível de qualquer lugar.",
    checks: [
      "Banco de dados na nuvem (AWS)",
      "Login com perfis diferentes",
      "Atualizações em tempo real",
      "Relatórios e dashboards",
    ],
    tag: { label: "Avançado", variant: "green" as const },
  },
  {
    icon: <Bot size="var(--size-22)" color="var(--color-surface)" />,
    id: "IA",
    accentColor: "var(--color-cyan-600)",
    color: "linear-gradient(var(--value-135deg), var(--color-cyan-600), var(--color-blue-600))",
    title: "IA e Chatbot Personalizado",
    sub: "Atendimento automático inteligente",
    desc: "Um assistente virtual no seu site que responde perguntas dos clientes, qualifica leads e automatiza atendimentos — treinado para o seu negócio.",
    checks: [
      "Chatbot com IA treinada",
      "Responde dúvidas 24h",
      "Integra com WhatsApp",
      "Otimizado para gastar menos em tokens",
    ],
    tag: { label: "Premium", variant: "blue" as const },
  },
];
